// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class GameVictoryPanel
    {
        #region Buttons
        [SerializeField] private CustomButton NextBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI TipsTxt;
        [SerializeField] private TextMeshProUGUI NextlevelTxt;
        #endregion

    }
