// This file is auto-generated by AutoUIBindEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class CommonBtn
    {
        #region Texts
        [SerializeField] private TextMeshProUGUI ContentTxt;
        #endregion

    }
