// This file is auto-generated by AutoUIBindEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class PropBlock
    {
        #region Buttons
        [SerializeField] private CustomButton ShopBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI CountTxt;
        #endregion

    }
