// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class GamePlayPanel
    {
        #region Buttons
        [SerializeField] private CustomButton PauseBtn;
        [SerializeField] private CustomButton ResetBtn;
        [SerializeField] private CustomButton ShopBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI LevelTxt;
        #endregion

    }
