// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class GamePlayPanel
    {
        #region Buttons
        [SerializeField] private CustomButton PauseBtn;
        [SerializeField] private CustomButton ResetBtn;
        [SerializeField] private CustomButton ShopBtn;
        [SerializeField] private CustomButton Skill1Btn;
        [SerializeField] private CustomButton Skill2Btn;
        [SerializeField] private CustomButton Skill3Btn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI LevelTxt;
        [SerializeField] private TextMeshProUGUI SkillContentTxt;
        #endregion

        #region Images
        [SerializeField] private Image UIYouxizhongZhezhao01Img;
        #endregion

    }
