// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class StartPanel
    {
        #region Buttons
        [SerializeField] private CustomButton GmBtn;
        [SerializeField] private CustomButton TestBtn;
        [SerializeField] private CustomButton SettingBtn;
        [SerializeField] private CustomButton PlayBtn;
        [SerializeField] private CustomButton ChoiceLevelBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI PlayTxt;
        #endregion

    }
