// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class GameTipsPopup
    {
        #region Buttons
        [SerializeField] private CustomButton CloseBtn;
        [SerializeField] private CustomButton YesBtn;
        [SerializeField] private CustomButton NoBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI TipTxt;
        [SerializeField] private TextMeshProUGUI Loading3Txt;
        [SerializeField] private TextMeshProUGUI YesTxt;
        [SerializeField] private TextMeshProUGUI NoTxt;
        #endregion

    }
