// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class RevivePopup
    {
        #region Buttons
        [SerializeField] private CustomButton CloseBtn;
        [SerializeField] private CustomButton ReviveBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI UiBoomi01Txt;
        #endregion

        #region Images
        [SerializeField] private Image UIBoomBk01Img;
        [SerializeField] private Image UIBoomTu01Img;
        #endregion

    }
