// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class Level43LoadingPopup
    {
        #region Texts
        [SerializeField] private TextMeshProUGUI UiJiazai1Txt;
        [SerializeField] private TextMeshProUGUI UiJiazai2Txt;
        [SerializeField] private TextMeshProUGUI UiJiazai3Txt;
        [SerializeField] private TextMeshProUGUI UiJiazai4Txt;
        #endregion

        #region Images
        [SerializeField] private Image UIJiazaiFaguangi01Img;
        #endregion

    }
