// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class GameSettingPopup
    {
        #region Buttons
        [SerializeField] private CustomButton CloseBtn;
        [SerializeField] private CustomButton ContactBtn;
        [SerializeField] private CustomButton HomeBtn;
        [SerializeField] private CustomButton LanguageBtn;
        [SerializeField] private CustomButton MenuBtn;
        [SerializeField] private CustomButton PrivacyPolicyBtn;
        [SerializeField] private CustomButton ResumeBtn;
        [SerializeField] private CustomButton TermsOfBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI LanguageTxt;
        [SerializeField] private TextMeshProUGUI MenuTxt;
        [SerializeField] private TextMeshProUGUI ResumeTxt;
        [SerializeField] private TextMeshProUGUI USettingsDes01Txt;
        [SerializeField] private TextMeshProUGUI USettingsDes02Txt;
        [SerializeField] private TextMeshProUGUI VersionTxt;
        #endregion

        #region Images
        [SerializeField] private List<Image> UISettingTiepian01Imgs;
        [SerializeField] private Image UISettingsBk01Img;
        #endregion

    }
