// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class GameSettingPopup
    {
        #region Buttons
        [SerializeField] private CustomButton CloseBtn;
        [SerializeField] private CustomButton LanguageBtn;
        [SerializeField] private CustomButton MenuBtn;
        [SerializeField] private CustomButton ResumeBtn;
        [SerializeField] private CustomButton PrivacyPolicyBtn;
        [SerializeField] private CustomButton ContactBtn;
        [SerializeField] private CustomButton TermsOfBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI TitleTxt;
        [SerializeField] private TextMeshProUGUI LanguageTxt;
        [SerializeField] private TextMeshProUGUI MenuTxt;
        [SerializeField] private TextMeshProUGUI ResumeTxt;
        [SerializeField] private TextMeshProUGUI VersionTxt;
        #endregion

    }
