
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Config.LubanConfig
{
public sealed partial class GlobalConst : Luban.BeanBase
{
    public GlobalConst(JSONNode _buf) 
    {
        { if(!_buf["test"].IsString) { throw new SerializationException(); }  Test = _buf["test"]; }
        { if(!_buf["tipCostCount"].IsNumber) { throw new SerializationException(); }  TipCostCount = _buf["tipCostCount"]; }
        { if(!_buf["showTipsFailCount"].IsNumber) { throw new SerializationException(); }  ShowTipsFailCount = _buf["showTipsFailCount"]; }
        { if(!_buf["showTipsTimeLimit"].IsNumber) { throw new SerializationException(); }  ShowTipsTimeLimit = _buf["showTipsTimeLimit"]; }
        { if(!_buf["ad_interstitialCD"].IsNumber) { throw new SerializationException(); }  AdInterstitialCD = _buf["ad_interstitialCD"]; }
        { if(!_buf["ad_rewardResetInterstitialCD"].IsNumber) { throw new SerializationException(); }  AdRewardResetInterstitialCD = _buf["ad_rewardResetInterstitialCD"]; }
        { if(!_buf["ad_interstitialShowMinLevel"].IsNumber) { throw new SerializationException(); }  AdInterstitialShowMinLevel = _buf["ad_interstitialShowMinLevel"]; }
        { if(!_buf["ad_interstitialShowIntervalCount"].IsNumber) { throw new SerializationException(); }  AdInterstitialShowIntervalCount = _buf["ad_interstitialShowIntervalCount"]; }
        { if(!_buf["ad_interstitialShowFailedCount"].IsNumber) { throw new SerializationException(); }  AdInterstitialShowFailedCount = _buf["ad_interstitialShowFailedCount"]; }
        { if(!_buf["showRatingLevel"].IsNumber) { throw new SerializationException(); }  ShowRatingLevel = _buf["showRatingLevel"]; }
    }

    public static GlobalConst DeserializeGlobalConst(JSONNode _buf)
    {
        return new LubanConfig.GlobalConst(_buf);
    }

    /// <summary>
    /// remote test
    /// </summary>
    public readonly string Test;
    /// <summary>
    /// 每次使用 tips 道具消耗
    /// </summary>
    public readonly int TipCostCount;
    /// <summary>
    /// 失败重置次数，展示提示
    /// </summary>
    public readonly int ShowTipsFailCount;
    /// <summary>
    /// 单次等待时间，展示提示
    /// </summary>
    public readonly float ShowTipsTimeLimit;
    /// <summary>
    /// 插屏展示CD
    /// </summary>
    public readonly int AdInterstitialCD;
    /// <summary>
    /// 激励视频后插屏 CD
    /// </summary>
    public readonly int AdRewardResetInterstitialCD;
    /// <summary>
    /// 插屏最小显示关卡数
    /// </summary>
    public readonly int AdInterstitialShowMinLevel;
    /// <summary>
    /// 插屏显示间隔数
    /// </summary>
    public readonly int AdInterstitialShowIntervalCount;
    /// <summary>
    /// 失败次数触发插屏 CD
    /// </summary>
    public readonly int AdInterstitialShowFailedCount;
    /// <summary>
    /// 展示评分系统弹窗关卡（通关展示）
    /// </summary>
    public readonly int ShowRatingLevel;
   
    public const int __ID__ = -903029478;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "test:" + Test + ","
        + "tipCostCount:" + TipCostCount + ","
        + "showTipsFailCount:" + ShowTipsFailCount + ","
        + "showTipsTimeLimit:" + ShowTipsTimeLimit + ","
        + "adInterstitialCD:" + AdInterstitialCD + ","
        + "adRewardResetInterstitialCD:" + AdRewardResetInterstitialCD + ","
        + "adInterstitialShowMinLevel:" + AdInterstitialShowMinLevel + ","
        + "adInterstitialShowIntervalCount:" + AdInterstitialShowIntervalCount + ","
        + "adInterstitialShowFailedCount:" + AdInterstitialShowFailedCount + ","
        + "showRatingLevel:" + ShowRatingLevel + ","
        + "}";
    }
}
}

