// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class GameFailedPanel
    {
        #region Buttons
        [SerializeField] private CustomButton RestartBtn;
        [SerializeField] private CustomButton UIShibai101Btn;
        #endregion

        #region Images
        [SerializeField] private Image UIShibaiSos01Img;
        [SerializeField] private Image UIShibaiTitle01Img;
        #endregion

    }
