// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class CommmonPopup
    {
        #region Buttons
        [SerializeField] private CustomButton CloseBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI UQuitDes01Txt;
        [SerializeField] private TextMeshProUGUI UQuitTitle01Txt;
        #endregion

    }
