// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class ChoiceLevelPanel
    {
        #region Buttons
        [SerializeField] private CustomButton SettingBtn;
        [SerializeField] private CustomButton ShopBtn;
        [SerializeField] private CustomButton NoAdBtn;
        [SerializeField] private CustomButton LastBtn;
        [SerializeField] private CustomButton NextBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI TitleTxt;
        #endregion

    }
