// This file is auto-generated by AutoUIBindEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class LevelChoiceItem
    {
        #region Buttons
        [SerializeField] private CustomButton ClickAreaBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI PassedTxt;
        [SerializeField] private TextMeshProUGUI CurrentTxt;
        [SerializeField] private TextMeshProUGUI AdLockTxt;
        [SerializeField] private TextMeshProUGUI NormalTxt;
        #endregion

        #region Images
        [SerializeField] private Image AdImg;
        #endregion

        #region GameObjects
        [SerializeField] private GameObject PassedState;
        [SerializeField] private GameObject CurrentState;
        [SerializeField] private GameObject AdLockState;
        [SerializeField] private GameObject NormalState;
        #endregion
    }
