// This file is auto-generated by UIGenerator postprocess (same rules as BaseUIViewEditor)
// You may use "Rescan & Regenerate Partial Script" on the view to refresh.


using Bear.UI;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

public partial class Setting
{
    #region Buttons
        [SerializeField] private CustomButton UISettingsYinxiao01Btn;
        [SerializeField] private CustomButton UISettingsYinyue01Btn;
        [SerializeField] private CustomButton UISettingsZhendong01Btn;
        [SerializeField] private CustomButton UISettings201Btn;
        [SerializeField] private CustomButton UISettings101Btn;
        [SerializeField] private CustomButton UIConmonX01Btn;
    #endregion

    #region Images
        [SerializeField] private Image UISettingsBk01Img;
        [SerializeField] private Image UISettingsJinyong01Img;
    #endregion

}
