
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Config
{
public sealed partial class Language : Luban.BeanBase
{
    public Language(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["contyrName"].IsString) { throw new SerializationException(); }  ContyrName = _buf["contyrName"]; }
        { if(!_buf["correspondingKey"].IsString) { throw new SerializationException(); }  CorrespondingKey = _buf["correspondingKey"]; }
        { if(!_buf["isOpen"].IsBoolean) { throw new SerializationException(); }  IsOpen = _buf["isOpen"]; }
    }

    public static Language DeserializeLanguage(JSONNode _buf)
    {
        return new Language(_buf);
    }

    /// <summary>
    /// LanguageID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 国家名称
    /// </summary>
    public readonly string ContyrName;
    public readonly string CorrespondingKey;
    /// <summary>
    /// 开启状态
    /// </summary>
    public readonly bool IsOpen;
   
    public const int __ID__ = -1548945544;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "contyrName:" + ContyrName + ","
        + "correspondingKey:" + CorrespondingKey + ","
        + "isOpen:" + IsOpen + ","
        + "}";
    }
}
}

