
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Config
{
public sealed partial class LevelSort : Luban.BeanBase
{
    public LevelSort(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["levelConfig"].IsString) { throw new SerializationException(); }  LevelConfig = _buf["levelConfig"]; }
        { if(!_buf["scene"].IsString) { throw new SerializationException(); }  Scene = _buf["scene"]; }
    }

    public static LevelSort DeserializeLevelSort(JSONNode _buf)
    {
        return new LevelSort(_buf);
    }

    /// <summary>
    /// uniqueID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡配置数据
    /// </summary>
    public readonly string LevelConfig;
    /// <summary>
    /// 关卡地图
    /// </summary>
    public readonly string Scene;
   
    public const int __ID__ = 347718434;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelConfig:" + LevelConfig + ","
        + "scene:" + Scene + ","
        + "}";
    }
}
}

