
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Config
{
public sealed partial class Products : Luban.BeanBase
{
    public Products(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["androidProductId"].IsString) { throw new SerializationException(); }  AndroidProductId = _buf["androidProductId"]; }
        { if(!_buf["iosProductId"].IsString) { throw new SerializationException(); }  IosProductId = _buf["iosProductId"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (IAP.ProductType)_buf["type"].AsInt; }
        { if(!_buf["rewardId"].IsString) { throw new SerializationException(); }  RewardId = _buf["rewardId"]; }
    }

    public static Products DeserializeProducts(JSONNode _buf)
    {
        return new Products(_buf);
    }

    public readonly string Id;
    /// <summary>
    /// 商品名称
    /// </summary>
    public readonly string AndroidProductId;
    /// <summary>
    /// 商品描述
    /// </summary>
    public readonly string IosProductId;
    /// <summary>
    /// 商品类型
    /// </summary>
    public readonly IAP.ProductType Type;
    /// <summary>
    /// 关联 Shop 奖励 Id
    /// </summary>
    public readonly string RewardId;
   
    public const int __ID__ = -939117180;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "androidProductId:" + AndroidProductId + ","
        + "iosProductId:" + IosProductId + ","
        + "type:" + Type + ","
        + "rewardId:" + RewardId + ","
        + "}";
    }
}
}

