
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Config
{
public sealed partial class Shop : Luban.BeanBase
{
    public Shop(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["goodsName"].IsString) { throw new SerializationException(); }  GoodsName = _buf["goodsName"]; }
        { if(!_buf["goodsDes"].IsString) { throw new SerializationException(); }  GoodsDes = _buf["goodsDes"]; }
        { if(!_buf["buyTimes"].IsNumber) { throw new SerializationException(); }  BuyTimes = _buf["buyTimes"]; }
        { var __json0 = _buf["rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } Rewards = new System.Collections.Generic.Dictionary<Game.GameProps, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Game.GameProps _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = (Game.GameProps)__e0[0].AsInt; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Rewards.Add(_k0, _v0); }   }
    }

    public static Shop DeserializeShop(JSONNode _buf)
    {
        return new Shop(_buf);
    }

    /// <summary>
    /// GoodsID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 商品名称
    /// </summary>
    public readonly string GoodsName;
    /// <summary>
    /// 商品描述
    /// </summary>
    public readonly string GoodsDes;
    /// <summary>
    /// 可购买次数
    /// </summary>
    public readonly int BuyTimes;
    /// <summary>
    /// 奖励内容
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<Game.GameProps, int> Rewards;
   
    public const int __ID__ = 2576150;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "goodsName:" + GoodsName + ","
        + "goodsDes:" + GoodsDes + ","
        + "buyTimes:" + BuyTimes + ","
        + "rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}
}

