
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Config
{
public partial class Tables
{
    public LubanConfig.TbGlobalConst TbGlobalConst {get; }
    public TbLanguage TbLanguage {get; }
    public TbLevelSort TbLevelSort {get; }
    public TbProducts TbProducts {get; }
    public TbShop TbShop {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbGlobalConst = new LubanConfig.TbGlobalConst(loader("lubanconfig_tbglobalconst"));
        TbLanguage = new TbLanguage(loader("tblanguage"));
        TbLevelSort = new TbLevelSort(loader("tblevelsort"));
        TbProducts = new TbProducts(loader("tbproducts"));
        TbShop = new TbShop(loader("tbshop"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGlobalConst.ResolveRef(this);
        TbLanguage.ResolveRef(this);
        TbLevelSort.ResolveRef(this);
        TbProducts.ResolveRef(this);
        TbShop.ResolveRef(this);
    }
}

}
