
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Config
{
public partial class TbLevelSort
{
    private readonly System.Collections.Generic.Dictionary<int, LevelSort> _dataMap;
    private readonly System.Collections.Generic.List<LevelSort> _dataList;
    
    public TbLevelSort(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelSort>(count);
        _dataList = new System.Collections.Generic.List<LevelSort>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LevelSort _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Config.LevelSort.DeserializeLevelSort(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LevelSort> DataMap => _dataMap;
    public System.Collections.Generic.List<LevelSort> DataList => _dataList;

    public LevelSort GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LevelSort Get(int key) => _dataMap[key];
    public LevelSort this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

