
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Config
{
public partial class TbProducts
{
    private readonly System.Collections.Generic.Dictionary<string, Products> _dataMap;
    private readonly System.Collections.Generic.List<Products> _dataList;
    
    public TbProducts(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Products>(count);
        _dataList = new System.Collections.Generic.List<Products>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Products _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Config.Products.DeserializeProducts(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Products> DataMap => _dataMap;
    public System.Collections.Generic.List<Products> DataList => _dataList;

    public Products GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Products Get(string key) => _dataMap[key];
    public Products this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

