
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Config
{
public partial class TbShop
{
    private readonly System.Collections.Generic.Dictionary<string, Shop> _dataMap;
    private readonly System.Collections.Generic.List<Shop> _dataList;
    
    public TbShop(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Shop>(count);
        _dataList = new System.Collections.Generic.List<Shop>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Shop _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Config.Shop.DeserializeShop(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Shop> DataMap => _dataMap;
    public System.Collections.Generic.List<Shop> DataList => _dataList;

    public Shop GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Shop Get(string key) => _dataMap[key];
    public Shop this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

