#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Bear.UI;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace Game.Editor
{
    /// <summary>
    /// UIGenerator 后处理：在与 Prefab 同级的 <c>Scripts</c> 目录下生成与 Prefab 同名的
    /// <c>partial BaseUIView</c> 主文件（仅首次）及扫描层级得到的 <c>.Generated.cs</c>（可反复覆盖）。
    /// 规则与 <see cref="BaseUIViewEditor"/> 中扫描命名一致（_btn / _txt / _img 等）。
    /// </summary>
    public static class UIGeneratorUIViewScriptGenerator
    {
        private const string GeneratedHeader =
            "// This file is auto-generated by UIGenerator postprocess (same rules as BaseUIViewEditor)\r\n" +
            "// You may use \"Rescan & Regenerate Partial Script\" on the view to refresh.\r\n";

        /// <summary>
        /// 由 <see cref="IUIGeneratorPostProcessor"/> 调用：写脚本、刷新资源，并在编译完成后把 View 挂到 Prefab 根。
        /// 如果类型已存在，则跳过生成，只更新 .Generated.cs 文件。
        /// </summary>
        public static void GenerateFromPrefabHierarchy(GameObject prefabRoot, string prefabAssetPath)
        {
            if (prefabRoot == null || string.IsNullOrEmpty(prefabAssetPath))
            {
                return;
            }

            prefabAssetPath = prefabAssetPath.Replace('\\', '/');
            string className = ToSafeClassName(Path.GetFileNameWithoutExtension(prefabAssetPath));

            // 优先检查类型是否已存在，避免创建不必要的文件夹
            if (TypeAlreadyExists(className))
            {
                Debug.Log($"[UIGeneratorUIViewScriptGenerator] Type '{className}' already exists in assembly, skipping all script generation.");
                Type existingType = ResolveType(className);
                if (existingType != null)
                {
                    TryAddComponentToPrefab(prefabAssetPath, existingType);
                }
                return;
            }

            string prefabDir = Path.GetDirectoryName(prefabAssetPath)?.Replace('\\', '/');
            if (string.IsNullOrEmpty(prefabDir))
            {
                Debug.LogWarning("[UIGeneratorUIViewScriptGenerator] Invalid prefab path.");
                return;
            }

            string scriptsDir = Path.Combine(prefabDir, "Scripts").Replace('\\', '/');
            if (!Directory.Exists(scriptsDir))
            {
                Directory.CreateDirectory(scriptsDir);
            }

            string mainPath = Path.Combine(scriptsDir, $"{className}.cs").Replace('\\', '/');
            string generatedPath = Path.Combine(scriptsDir, $"{className}.Generated.cs").Replace('\\', '/');

            bool mainScriptExists = File.Exists(mainPath);

            // 只有当主脚本不存在时才生成主脚本
            if (!mainScriptExists)
            {
                EnsureMainScript(mainPath, className);
                Debug.Log($"[UIGeneratorUIViewScriptGenerator] Created main script: {mainPath}");
            }
            else
            {
                Debug.Log($"[UIGeneratorUIViewScriptGenerator] Main script already exists: {mainPath}");
            }

            // 生成 Generated.cs 文件
            List<UIComponentInfo> components = ScanChildObjects(prefabRoot);
            string generatedCode = BuildGeneratedPartial(className, components);
            File.WriteAllText(generatedPath, generatedCode, Encoding.UTF8);

            AssetDatabase.ImportAsset(generatedPath);
            if (!mainScriptExists)
            {
                AssetDatabase.ImportAsset(mainPath);
            }
            AssetDatabase.Refresh();

            // 编译完成后添加组件
            PendingPrefabViewAttach.Enqueue(prefabAssetPath, className);

            Debug.Log(
                $"[UIGeneratorUIViewScriptGenerator] Scripts: {mainPath}, {generatedPath} (components: {components.Count})");
        }

        /// <summary>
        /// 尝试将 View 组件添加到 Prefab 根节点（如果不存在）
        /// </summary>
        private static void TryAddComponentToPrefab(string prefabPath, Type viewType)
        {
            GameObject contents = PrefabUtility.LoadPrefabContents(prefabPath);
            try
            {
                if (contents.GetComponent(viewType) != null)
                {
                    return;
                }

                contents.AddComponent(viewType);
                PrefabUtility.SaveAsPrefabAsset(contents, prefabPath);
                AssetDatabase.ImportAsset(prefabPath);
                Debug.Log($"[UIGeneratorUIViewScriptGenerator] Added {viewType.Name} to prefab root: {prefabPath}");
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(contents);
            }
        }

        /// <summary>
        /// 检查指定名称的类型是否已存在于当前程序域中
        /// </summary>
        private static bool TypeAlreadyExists(string className)
        {
            return ResolveType(className) != null;
        }

        /// <summary>
        /// 解析类型（从 PendingPrefabViewAttach 移出来作为公共方法）
        /// </summary>
        private static Type ResolveType(string className)
        {
            foreach (System.Reflection.Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try
                {
                    types = assembly.GetTypes();
                }
                catch
                {
                    continue;
                }

                foreach (Type t in types)
                {
                    if (t.Name == className && typeof(BaseUIView).IsAssignableFrom(t))
                    {
                        return t;
                    }
                }
            }

            return null;
        }

        private static void EnsureMainScript(string mainPath, string className)
        {
            if (File.Exists(mainPath))
            {
                return;
            }

            string body =
                "using Bear.UI;\r\n" +
                "using UnityEngine;\r\n" +
                "\r\n" +
                $"public partial class {className} : BaseUIView\r\n" +
                "{\r\n" +
                "    public override void OnOpen()\r\n" +
                "    {\r\n" +
                "        base.OnOpen();\r\n" +
                "    }\r\n" +
                "\r\n" +
                "    public override void OnCreate()\r\n" +
                "    {\r\n" +
                "        base.OnCreate();\r\n" +
                "        // TODO: 注册按钮等（示例见 PictureVerifticationPopup）\r\n" +
                "    }\r\n" +
                "\r\n" +
                "    public override void OnClose()\r\n" +
                "    {\r\n" +
                "        base.OnClose();\r\n" +
                "    }\r\n" +
                "\r\n" +
                $"    public static {className} Create()\r\n" +
                "    {\r\n" +
                "        var panel = UIManager.Instance.OpenUI<" + className + ">($\"" + "{typeof(" + className + ").Name}\", UILayer.Normal);\r\n" +
                "        return panel;\r\n" +
                "    }\r\n" +
                "}\r\n";

            File.WriteAllText(mainPath, body, Encoding.UTF8);
        }

        private static string ToSafeClassName(string raw)
        {
            if (string.IsNullOrEmpty(raw))
            {
                return "GeneratedUIView";
            }

            var sb = new StringBuilder();
            for (int i = 0; i < raw.Length; i++)
            {
                char c = raw[i];
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(c);
                }
                else
                {
                    sb.Append('_');
                }
            }

            string s = sb.ToString().Trim('_');
            if (s.Length == 0)
            {
                return "GeneratedUIView";
            }

            if (char.IsDigit(s[0]))
            {
                s = "U_" + s;
            }

            return s;
        }

        #region Scan (aligned with BaseUIViewEditor)

        private sealed class UIComponentInfo
        {
            public string Name { get; set; }
            public string Type { get; set; }
            public string FieldName { get; set; }
        }

        private static List<UIComponentInfo> ScanChildObjects(GameObject parent)
        {
            var list = new List<UIComponentInfo>();
            ScanChildObjectsRecursive(parent.transform, list);
            return list;
        }

        private static void ScanChildObjectsRecursive(Transform parent, List<UIComponentInfo> components)
        {
            foreach (Transform child in parent)
            {
                GameObject obj = child.gameObject;

                if (obj.GetComponent<BaseAutoUIBind>() != null || obj.GetComponent<BaseUIView>() != null)
                {
                    continue;
                }

                if (child.name.StartsWith("-", StringComparison.Ordinal))
                {
                    continue;
                }

                string objectName = child.name;

                if (objectName.Contains("_btn", StringComparison.Ordinal))
                {
                    CustomButton btn = obj.GetComponent<CustomButton>();
                    if (btn != null)
                    {
                        components.Add(new UIComponentInfo
                        {
                            Name = objectName,
                            Type = "CustomButton",
                            FieldName = GetFieldName(objectName)
                        });
                    }
                }

                if (objectName.Contains("_txt", StringComparison.Ordinal))
                {
                    TextMeshProUGUI txt = obj.GetComponent<TextMeshProUGUI>();
                    if (txt != null)
                    {
                        components.Add(new UIComponentInfo
                        {
                            Name = objectName,
                            Type = "TextMeshProUGUI",
                            FieldName = GetFieldName(objectName)
                        });
                    }
                }

                if (objectName.Contains("_img", StringComparison.Ordinal))
                {
                    Image img = obj.GetComponent<Image>();
                    if (img != null)
                    {
                        components.Add(new UIComponentInfo
                        {
                            Name = objectName,
                            Type = "Image",
                            FieldName = GetFieldName(objectName)
                        });
                    }
                }

                if (objectName.Contains("_toggle", StringComparison.Ordinal))
                {
                    Toggle toggle = obj.GetComponent<Toggle>();
                    if (toggle != null)
                    {
                        components.Add(new UIComponentInfo
                        {
                            Name = objectName,
                            Type = "Toggle",
                            FieldName = GetFieldName(objectName)
                        });
                    }
                }

                if (objectName.Contains("_state", StringComparison.Ordinal))
                {
                    components.Add(new UIComponentInfo
                    {
                        Name = objectName,
                        Type = "GameObject",
                        FieldName = GetFieldName(objectName)
                    });
                }

                ScanChildObjectsRecursive(child, components);
            }
        }

        private static string GetFieldName(string objectName)
        {
            string fieldName = objectName;
            string suffix = "";

            if (fieldName.Contains("_btn", StringComparison.Ordinal))
            {
                suffix = "Btn";
                fieldName = fieldName.Replace("_btn", "");
            }
            else if (fieldName.Contains("_txt", StringComparison.Ordinal))
            {
                suffix = "Txt";
                fieldName = fieldName.Replace("_txt", "");
            }
            else if (fieldName.Contains("_img", StringComparison.Ordinal))
            {
                suffix = "Img";
                fieldName = fieldName.Replace("_img", "");
            }
            else if (fieldName.Contains("_toggle", StringComparison.Ordinal))
            {
                suffix = "Toggle";
                fieldName = fieldName.Replace("_toggle", "");
            }
            else if (fieldName.Contains("_state", StringComparison.Ordinal))
            {
                suffix = "State";
                fieldName = fieldName.Replace("_state", "");
            }

            string[] parts = fieldName.Split('_');
            var sb = new StringBuilder();
            foreach (string part in parts)
            {
                if (part.Length > 0)
                {
                    sb.Append(char.ToUpperInvariant(part[0]));
                    if (part.Length > 1)
                    {
                        sb.Append(part.Substring(1));
                    }
                }
            }

            if (!string.IsNullOrEmpty(suffix))
            {
                sb.Append(suffix);
            }

            return sb.ToString();
        }

        #endregion

        private static string BuildGeneratedPartial(string className, List<UIComponentInfo> components)
        {
            var code = new StringBuilder();
            code.AppendLine(GeneratedHeader);
            code.AppendLine();
            code.AppendLine("using Bear.UI;");
            code.AppendLine("using UnityEngine;");
            code.AppendLine("using UnityEngine.UI;");
            code.AppendLine("using TMPro;");
            code.AppendLine();
            code.AppendLine($"public partial class {className}");
            code.AppendLine("{");

            var buttons = components.Where(c => c.Type == "CustomButton").ToList();
            var texts = components.Where(c => c.Type == "TextMeshProUGUI").ToList();
            var images = components.Where(c => c.Type == "Image").ToList();
            var toggles = components.Where(c => c.Type == "Toggle").ToList();
            var gameObjects = components.Where(c => c.Type == "GameObject").ToList();

            AppendRegion(code, "Buttons", buttons, c => $"[SerializeField] private CustomButton {c.FieldName};");
            AppendRegion(code, "Texts", texts, c => $"[SerializeField] private TextMeshProUGUI {c.FieldName};");
            AppendRegion(code, "Images", images, c => $"[SerializeField] private Image {c.FieldName};");
            AppendRegion(code, "Toggles", toggles, c => $"[SerializeField] private Toggle {c.FieldName};");
            AppendRegion(code, "GameObjects", gameObjects, c => $"[SerializeField] private GameObject {c.FieldName};");

            code.AppendLine("}");
            return code.ToString();
        }

        private static void AppendRegion(
            StringBuilder code,
            string regionName,
            List<UIComponentInfo> items,
            Func<UIComponentInfo, string> line)
        {
            if (items.Count == 0)
            {
                return;
            }

            code.AppendLine($"    #region {regionName}");
            foreach (UIComponentInfo c in items)
            {
                code.AppendLine($"        {line(c)}");
            }

            code.AppendLine("    #endregion");
            code.AppendLine();
        }

        /// <summary>编译完成后给 Prefab 根挂上生成的 View（若尚未挂载）。</summary>
        private static class PendingPrefabViewAttach
        {
            private static readonly List<(string prefabPath, string className)> Queue = new List<(string, string)>();
            private static bool _updateHooked;
            private static int _waitTicks;

            private const int MaxWaitTicks = 600;

            public static void Enqueue(string prefabPath, string className)
            {
                prefabPath = prefabPath.Replace('\\', '/');
                Queue.Add((prefabPath, className));
                if (!_updateHooked)
                {
                    _updateHooked = true;
                    EditorApplication.update += OnEditorUpdate;
                }
            }

            private static void OnEditorUpdate()
            {
                if (Queue.Count == 0)
                {
                    EditorApplication.update -= OnEditorUpdate;
                    _updateHooked = false;
                    _waitTicks = 0;
                    return;
                }

                (string prefabPath, string className) = Queue[0];
                Type viewType = UIGeneratorUIViewScriptGenerator.ResolveType(className);
                if (viewType == null)
                {
                    _waitTicks++;
                    if (_waitTicks < MaxWaitTicks)
                    {
                        return;
                    }

                    Debug.LogError(
                        $"[UIGeneratorUIViewScriptGenerator] Timeout waiting for compiled type '{className}'. " +
                        "Fix compile errors, then add the View to the prefab manually or re-run UI Generator.");
                    Queue.RemoveAt(0);
                    _waitTicks = 0;
                    return;
                }

                _waitTicks = 0;

                if (!typeof(BaseUIView).IsAssignableFrom(viewType))
                {
                    Debug.LogWarning($"[UIGeneratorUIViewScriptGenerator] {className} is not a BaseUIView.");
                    Queue.RemoveAt(0);
                    return;
                }

                TryAddComponentToPrefab(prefabPath, viewType);
                Queue.RemoveAt(0);

                if (Queue.Count == 0)
                {
                    EditorApplication.update -= OnEditorUpdate;
                    _updateHooked = false;
                }
            }

            // ResolveType 和 TryAddComponentToPrefab 已移至类级别作为公共方法
        }
    }
}
#endif
