// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class RatingPopup
    {
        #region Buttons
        [SerializeField] private CustomButton CloseBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI URateDes01Txt;
        #endregion

        #region Images
        [SerializeField] private List<Image> UIPingfenDicengxing01Imgs;
        [SerializeField] private List<Image> UIPingfenZhuyaoxing01Imgs;
        [SerializeField] private Image UIPingfenBak01Img;
        #endregion

        #region Toggles
        [SerializeField] private List<Toggle> UIPingfenXing01Toggles;
        #endregion

    }
