
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Config.Game
{ 
    public enum GameProps
    {
        /// <summary>
        /// 提示
        /// </summary>
        Tips = 1,
        /// <summary>
        /// 无限提示
        /// </summary>
        UnlimitTips = 2,
        /// <summary>
        /// 免广告
        /// </summary>
        NoAds = 100,
    }

} 

