
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Config.Game
{ 
    public enum InterstitialPlacement
    {
        /// <summary>
        /// 游戏失败
        /// </summary>
        InGameFailed = 0,
        /// <summary>
        /// 游戏胜利
        /// </summary>
        InGameVictory = 1,
        /// <summary>
        /// 测试用
        /// </summary>
        GameTest = -1,
    }

} 

