
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Config.Game
{ 
    public enum RewardPlacement
    {
        /// <summary>
        /// 测试用 
        /// </summary>
        GameTest = -1,
        /// <summary>
        /// 游戏提示
        /// </summary>
        InGameTips = 0,
        /// <summary>
        /// 游戏通关
        /// </summary>
        InGamePassLevel = 1,
        /// <summary>
        /// 解锁关卡
        /// </summary>
        OutGameUnlockLevel = 2,
    }

} 

