// This file is auto-generated by AutoUIBindEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class ShopItem
    {
        #region Texts
        [SerializeField] private TextMeshProUGUI ItemContentTxt;
        [SerializeField] private TextMeshProUGUI ItemNameTxt;
        #endregion

    }
