// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class ShopPanel
    {
        #region Buttons
        [SerializeField] private CustomButton CloseBtn;
        [SerializeField] private CustomButton RestoreBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI ShopTxt;
        #endregion

    }
