// This file is auto-generated by UIGenerator postprocess (same rules as BaseUIViewEditor)
// You may use "Rescan & Regenerate Partial Script" on the view to refresh.


using Bear.UI;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

public partial class VictoryPanel
{
    #region Images
        [SerializeField] private Image UIShengliLinshi01Img;
    #endregion

}
