// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class PictureVerifticationPopup
    {
        #region Buttons
        [SerializeField] private CustomButton ResetBtn;
        [SerializeField] private CustomButton CheckBtn;
        [SerializeField] private CustomButton CloseBtn;
        #endregion

    }
