// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class PicVerificationStep1Popup
    {
        #region Buttons
        [SerializeField] private CustomButton CloseBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI SLeveltipsDesLevelTxt;
        [SerializeField] private TextMeshProUGUI SLeveltipsDesLevel2Txt;
        #endregion

        #region Images
        [SerializeField] private Image RjyzBgImg;
        [SerializeField] private Image RjyzBg2Img;
        [SerializeField] private Image RjyzGouImg;
        [SerializeField] private Image RjyzTb1Img;
        #endregion

        #region Toggles
        [SerializeField] private Toggle UIRjyzXzk01Toggle;
        #endregion

    }
