
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Config.IAP
{ 
    public enum ProductType
    {
        /// <summary>
        /// 永久有效
        /// </summary>
        Possessive = 0,
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumeable = 1,
        /// <summary>
        /// 订阅制
        /// </summary>
        Subscriptions = 2,
    }

} 

