// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class NoAdsPopup
    {
        #region Buttons
        [SerializeField] private CustomButton CloseBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI ContentTxt;
        #endregion

    }
