// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class GMPanel
    {
        #region Buttons
        [SerializeField] private CustomButton DebugBtn;
        [SerializeField] private CustomButton DeleteBtn;
        [SerializeField] private CustomButton EnterLevelLoadingBtn;
        [SerializeField] private CustomButton InterstitialBtn;
        [SerializeField] private CustomButton LastLevelBtn;
        [SerializeField] private CustomButton NextLevelBtn;
        [SerializeField] private CustomButton RatingPopupBtn;
        [SerializeField] private CustomButton RestoreBtn;
        [SerializeField] private CustomButton RewardAdBtn;
        [SerializeField] private CustomButton SwitchBtn;
        [SerializeField] private CustomButton UnlockBtn;
        [SerializeField] private CustomButton VictoryBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI SwitchTxt;
        #endregion

    }
