// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class GMPasswordPopup
    {
        #region Buttons
        [SerializeField] private CustomButton CloseBtn;
        [SerializeField] private CustomButton YesBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI YesTxt;
        #endregion

    }
